version: '3.7'

services:
    # imagem deojj
    deojj:
        container_name: deojj_app
        build:
            args:
                user: gustavo
                uid : 1000
            context: ./
            dockerfile: Dockerfile
        image: telebio-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - microservices

    # nginx
    nginx:
        container_name: deojj_nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8000:80
            - 443:443
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - microservices

    # postgres

    db_deojj:
        container_name: deojj_db
        image: postgres:12.0-alpine
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}

        volumes:
            - deojj_db:/var/lib/postgresql/data
        ports:
            - 5438:5432
        networks:
            - microservices

volumes:
    deojj_db:

networks:
    microservices:
        driver: bridge
